export const IS_LOADING = "IS_LOADING";
export const ADD_TO_WISHLIST = "ADD_TO_WISHLIST";
export const REMOVE_FROM_WISHLIST = "REMOVE_FROM_WISHLIST";
export const GET_ITEMS_FROM_WISHLIST = "GET_ITEMS_FROM_WISHLIST";
export const IS_ERROR = "IS_ERROR";
